# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 80, 270, 3))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(340, 30, 3, 200))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(225, 225, 225);")
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(510, 40, 41, 31))
        self.toolButton.setStyleSheet("background-color: rgb(60, 63, 65);\n"
"selection-background-color: rgb(60, 63, 65);\n"
"color: rgb(225, 225, 225);")
        self.toolButton.setObjectName("toolButton")
        self.toolButton.clicked.connect(self.openfile)

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 271, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_diameter = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_diameter.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_diameter.setObjectName("horizontalLayout_diameter")
        self.label_text = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("color: rgb(225, 225, 225);")
        self.label_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_text.setObjectName("label_text")
        self.horizontalLayout_diameter.addWidget(self.label_text)
        self.diameter = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.diameter.setFont(font)
        self.diameter.setStyleSheet("background-color: rgb(60, 63, 65);\n"
"color: rgb(225, 225, 225);")
        self.diameter.setObjectName("diameter")
        self.horizontalLayout_diameter.addWidget(self.diameter)
        self.label_2_text = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2_text.setFont(font)
        self.label_2_text.setStyleSheet("color: rgb(225, 225, 225);")
        self.label_2_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2_text.setObjectName("label_2_text")
        self.horizontalLayout_diameter.addWidget(self.label_2_text)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(60, 63, 65);\n"
"color: rgb(230, 230, 230);\n"
"selection-background-color: rgb(0, 170, 255);")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setGeometry(QtCore.QRect(339, 102, 183, 125))
        self.menu.setMouseTracking(True)
        self.menu.setStyleSheet("selection-background-color: rgb(0, 170, 255);")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.instraction = QtGui.QAction(MainWindow)
        self.instraction.setObjectName("instraction")
        self.about = QtGui.QAction(MainWindow)
        self.about.setObjectName("about")
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.menu.addAction(self.instraction)
        self.menu.addAction(self.about)
        self.menu.addSeparator()
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IV Converter"))
        self.label.setText(_translate("MainWindow", "Открыть файл:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_text.setText(_translate("MainWindow", "Диаметр контакта:"))
        self.diameter.setInputMask(_translate("MainWindow", "0.0000"))
        self.diameter.setText(_translate("MainWindow", "0.0000"))
        self.label_2_text.setText(_translate("MainWindow", "мкм"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.instraction.setText(_translate("MainWindow", "Инструкция"))
        self.about.setText(_translate("MainWindow", "О программе"))
        self.exit.setText(_translate("MainWindow", "Выход"))

    def openfile(self):
        file_name = QtWidgets.QFileDialog.getOpenFileName()[0]
        print(file_name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
